INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('PHYS2662', 'Electromagnetism', 123);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('PSYC2053', 'Abnormal Psychology', 161);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('COMP1348', 'Software Engineering', 95);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('GEND2990', 'Gender Studies', 168);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('BIOL3441', 'Anatomy', 149);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('ECON1036', 'Econometrics', 15);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('GEND3157', 'Feminist Theory', 10);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('COMP1522', 'Operating Systems', 70);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('GEND4807', 'Feminist Theory', 35);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('MATH1047', 'Calculus I', 80);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('MATH2899', 'Abstract Algebra', 44);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('MATH1408', 'Calculus I', 35);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('BIOL2571', 'Evolution', 22);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('MATH2393', 'Real Analysis', 131);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('BIOL1965', 'Evolution', 83);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('PHYS4206', 'Quantum Mechanics', 71);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('PHYS1431', 'Electromagnetism', 167);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('GEND2219', 'Gender Studies', 128);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('GEND2849', 'Queer Theory', 126);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('LAW3450', 'Criminal Law', 72);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('COMP2047', 'Software Engineering', 84);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('GEND1187', 'Feminist Theory', 8);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('ECON3854', 'Econometrics', 200);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('BIOL1527', 'Evolution', 75);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('BIOL4857', 'Genetics', 101);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('COMP3310', 'AI Fundamentals', 150);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('LAW2110', 'Contract Law', 29);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('COMP3894', 'Operating Systems', 76);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('CHEM3603', 'Inorganic Chemistry', 47);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('LAW4552', 'International Law', 190);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('BIOL4085', 'Evolution', 158);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('PHYS1098', 'Mechanics', 46);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('BIOL1647', 'Molecular Biology', 45);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('LAW2717', 'Contract Law', 17);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('LAW1696', 'Criminal Law', 119);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('PSYC2560', 'Abnormal Psychology', 57);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('PHYS4837', 'General Physics', 79);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('PHYS2411', 'Electromagnetism', 44);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('MATH1145', 'Abstract Algebra', 136);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('MATH4327', 'Real Analysis', 110);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('ECON3868', 'Macroeconomics', 195);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('PHYS3703', 'Thermodynamics', 89);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('MATH1491', 'Differential Equations', 171);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('MATH4429', 'Calculus I', 148);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('GEND2390', 'Gender Studies', 38);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('CHEM3683', 'Physical Chemistry', 175);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('PSYC1306', 'Abnormal Psychology', 107);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('ECON1290', 'Microeconomics', 129);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('ECON2772', 'Macroeconomics', 179);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('MATH1504', 'Calculus I', 160);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('PSYC4292', 'Intro to Psychology', 87);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('ECON2296', 'Microeconomics', 77);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('GEND2048', 'Gender Studies', 115);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('LAW4411', 'International Law', 13);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('BIOL4054', 'Genetics', 59);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('PHYS1487', 'General Physics', 165);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('CHEM3440', 'Biochemistry', 92);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('GEND4350', 'Feminist Theory', 98);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('PSYC3155', 'Research Methods', 34);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('LAW2466', 'Contract Law', 154);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('PHYS3968', 'Thermodynamics', 75);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('MATH4512', 'Differential Equations', 125);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('GEND3013', 'Gender Studies', 182);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('PHYS2368', 'Thermodynamics', 98);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('MATH2238', 'Linear Algebra', 34);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('GEND1856', 'Gender Studies', 114);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('LAW4860', 'Human Rights Law', 106);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('CHEM1519', 'Physical Chemistry', 164);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('CHEM1458', 'Biochemistry', 22);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('BIOL2782', 'Anatomy', 178);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('ECON3720', 'Development Economics', 1);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('ECON3053', 'Development Economics', 108);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('CHEM3767', 'Inorganic Chemistry', 185);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('MATH2283', 'Calculus I', 174);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('BIOL2579', 'Genetics', 147);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('PSYC2893', 'Cognitive Psychology', 45);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('PSYC3665', 'Research Methods', 145);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('PHYS4465', 'Electromagnetism', 25);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('LAW2166', 'Contract Law', 65);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('PHYS4393', 'Quantum Mechanics', 36);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('ECON3580', 'Macroeconomics', 137);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('LAW2312', 'Human Rights Law', 67);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('GEND1827', 'Feminist Theory', 86);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('BIOL4154', 'Evolution', 15);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('ECON4891', 'Econometrics', 78);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('CHEM4061', 'Inorganic Chemistry', 169);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('CHEM2705', 'Physical Chemistry', 13);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('ECON4522', 'Development Economics', 186);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('COMP3631', 'Data Structures', 142);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('GEND2527', 'Gender and Media', 19);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('ECON1146', 'Econometrics', 111);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('ECON1809', 'Macroeconomics', 69);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('GEND4186', 'Feminist Theory', 198);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('PHYS2869', 'Electromagnetism', 62);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('BIOL3277', 'Cell Biology', 61);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('PSYC3006', 'Abnormal Psychology', 117);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('LAW2956', 'International Law', 138);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('ECON4781', 'Macroeconomics', 99);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('GEND3861', 'Gender and Media', 141);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('COMP1778', 'Software Engineering', 43);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('GEND3399', 'Feminist Theory', 153);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('PHYS4043', 'Quantum Mechanics', 169);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('BIOL1430', 'Evolution', 105);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('GEND4682', 'Feminist Theory', 144);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('GEND2747', 'Queer Theory', 55);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('ECON4593', 'Econometrics', 114);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('ECON1411', 'Econometrics', 31);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('MATH2245', 'Linear Algebra', 88);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('COMP4456', 'Software Engineering', 14);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('ECON3890', 'Development Economics', 130);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('MATH1771', 'Linear Algebra', 100);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('ECON3991', 'Macroeconomics', 38);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('COMP3190', 'Operating Systems', 91);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('GEND2837', 'Feminist Theory', 14);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('GEND4715', 'Feminist Theory', 82);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('COMP3707', 'Intro to Programming', 124);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('ECON1548', 'Microeconomics', 182);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('CHEM2901', 'Biochemistry', 75);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('COMP4505', 'Data Structures', 6);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('PHYS2116', 'General Physics', 66);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('PSYC2072', 'Research Methods', 85);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('LAW2950', 'Human Rights Law', 175);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('MATH1651', 'Linear Algebra', 137);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('COMP2994', 'Software Engineering', 146);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('GEND4548', 'Queer Theory', 20);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('GEND3694', 'Gender and Media', 72);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('ECON2952', 'Econometrics', 14);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('CHEM1756', 'Physical Chemistry', 8);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('GEND4342', 'Gender Studies', 60);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('BIOL3621', 'Cell Biology', 122);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('MATH3848', 'Real Analysis', 194);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('BIOL4160', 'Molecular Biology', 193);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('ECON1459', 'Development Economics', 145);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('COMP1947', 'AI Fundamentals', 194);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('CHEM4610', 'Physical Chemistry', 4);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('GEND4356', 'Feminist Theory', 1);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('MATH2259', 'Differential Equations', 135);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('PSYC4737', 'Cognitive Psychology', 120);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('PHYS2409', 'Electromagnetism', 114);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('GEND4051', 'Queer Theory', 176);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('BIOL1480', 'Evolution', 162);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('PSYC3092', 'Abnormal Psychology', 11);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('BIOL4590', 'Evolution', 139);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('PSYC1553', 'Research Methods', 9);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('CHEM4477', 'Organic Chemistry', 194);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('COMP3230', 'Operating Systems', 155);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('PHYS1439', 'Electromagnetism', 63);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('CHEM4314', 'Inorganic Chemistry', 128);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('GEND1786', 'Gender and Media', 96);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('LAW1668', 'Human Rights Law', 51);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('COMP3205', 'Operating Systems', 184);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('COMP3685', 'Operating Systems', 173);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('PHYS1402', 'Quantum Mechanics', 35);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('PHYS1814', 'Electromagnetism', 78);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('BIOL2986', 'Evolution', 26);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('GEND3181', 'Gender and Media', 37);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('CHEM3998', 'Biochemistry', 146);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('ECON4696', 'Macroeconomics', 118);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('CHEM4532', 'Inorganic Chemistry', 38);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('COMP4445', 'Operating Systems', 77);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('MATH3980', 'Linear Algebra', 22);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('ECON1002', 'Development Economics', 156);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('GEND4718', 'Gender and Media', 23);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('CHEM4871', 'Biochemistry', 165);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('ECON1714', 'Microeconomics', 121);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('GEND4467', 'Queer Theory', 141);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('BIOL4220', 'Cell Biology', 12);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('COMP1732', 'AI Fundamentals', 49);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('PSYC4918', 'Cognitive Psychology', 42);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('ECON3814', 'Econometrics', 78);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('BIOL2732', 'Anatomy', 183);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('GEND3298', 'Feminist Theory', 113);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('BIOL4703', 'Evolution', 42);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('ECON3820', 'Econometrics', 128);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('CHEM2018', 'Inorganic Chemistry', 61);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('COMP3192', 'Intro to Programming', 197);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('GEND1235', 'Feminist Theory', 109);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('PSYC3102', 'Research Methods', 3);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('COMP2327', 'Intro to Programming', 187);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('PSYC4993', 'Abnormal Psychology', 127);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('ECON1262', 'Econometrics', 32);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('PHYS4102', 'Quantum Mechanics', 18);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('LAW1708', 'Human Rights Law', 133);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('PHYS3211', 'General Physics', 53);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('ECON4972', 'Macroeconomics', 177);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('BIOL4770', 'Anatomy', 102);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('MATH1862', 'Real Analysis', 50);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('BIOL3866', 'Cell Biology', 196);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('GEND4804', 'Gender and Media', 162);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('CHEM1242', 'Organic Chemistry', 104);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('PHYS2598', 'Electromagnetism', 188);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('ECON3459', 'Econometrics', 151);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('LAW1254', 'Criminal Law', 166);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('ECON1668', 'Development Economics', 197);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('BIOL1626', 'Evolution', 73);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('PSYC1645', 'Intro to Psychology', 112);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('PSYC1328', 'Abnormal Psychology', 51);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('PHYS4009', 'Thermodynamics', 94);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('CHEM2362', 'Organic Chemistry', 170);
INSERT INTO Courses (CourseCode, CourseName, LecturerID) VALUES ('GEND4491', 'Feminist Theory', 92);